<a href="https://colab.research.google.com/github/Varshitha0702/B2_PFDS_1103/blob/main/PFDS_L2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Create a 2D NumPy array for student marks in 3 subjects

In [ ]:
import numpy as np
arr = np.array([[69,70,80],[80,95,95],[88,96,99]])
print(arr)

[[69 70 80]
 [80 95 95]
 [88 96 99]]


## Calculate average, minimum, and maximum marks

In [ ]:
mean=np.mean(arr)
print(mean)
minimum=np.min(arr)
print(minimum)
maximum=np.max(arr)
print(maximum)

85.77777777777777
69
99


In [ ]:
for i in range(len(arr)):
    print(f"Student {i+1}: Marks = {arr[i]}, Avg = {average_per_student[i]:.2f}, Min = {min_per_student[i]}, Max = {max_per_student[i]}")

Student 1: Marks = [69 70 80], Avg = 73.00, Min = 69, Max = 80
Student 2: Marks = [80 95 95], Avg = 90.00, Min = 80, Max = 95
Student 3: Marks = [88 96 99], Avg = 94.33, Min = 88, Max = 99


## Use slicing to retrieve marks of specific students

In [ ]:
# Use slicing to retrieve marks of specific students
print("Marks of Student 1:",arr[0:1])

Marks of Student 1: [[69 70 80]]


## Use boolean indexing to find students scoring above 80


In [ ]:
above_80 = arr > 80
print("Boolean Array (Scores > 80):\n", above_80)

Boolean Array (Scores > 80):
 [[False False False]
 [False  True  True]
 [ True  True  True]]


## Reshape the array to observe subject-wise performance

In [ ]:
subject_wise = arr.T
print("\n Subject-wise Performance (Rows = Subjects):\n", subject_wise)


 Subject-wise Performance (Rows = Subjects):
 [[69 80 88]
 [70 95 96]
 [80 95 99]]
